# -----------------------------------------
# Notes:
#
# -----------------------------------------
# Example Workflow:

name: Generate Table of Contents

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  workflow_dispatch:

jobs:
  toc:
    name: Generate TOC
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CREATE_PR: true
          # TARGET_BRANCH_PREFIX: release/
